[project]
name = 'prediction-market'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.prediction-market]
path = 'contracts/prediction-market.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
